name: DeaDBeeF Nightly Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 7 1/7 * *"
  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "Build AppImage"
            arch: x86_64
#          - runs-on: ubuntu-24.04-arm
#            name: "Build AppImage"
#            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Get dependencies
      run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

    - name: Make AppImage
      run: |
        chmod +x ./*-appimage.sh && ./*-appimage.sh devel
        mkdir dist
        mv *.AppImage* dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: AppImage-${{ matrix.arch }}
        path: 'dist'

    - name: Upload version file
      uses: actions/upload-artifact@v4.6.2
      with:
       name: version
       path: ~/version
       overwrite: true

  release:
      if: ${{ github.ref_name == 'main' }}
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.3.0
          with:
            name: AppImage-x86_64

#        - uses: actions/download-artifact@v4.3.0
#          with:
#            name: AppImage-aarch64

        - uses: actions/download-artifact@v4.3.0
          with:
            name: version

        - name: Read version
          run: |
            cat version
            export VERSION="$(cat version)"
            echo "APP_VERSION=${VERSION}" >> "${GITHUB_ENV}"

        #Version Release
        - name: Del Previous Release
          run: |
            gh release delete "nightly" --repo "${GITHUB_REPOSITORY}" --cleanup-tag  -y
            sleep 5
          env:
            GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          continue-on-error: true
  
        - uses: softprops/action-gh-release@v2.2.2
          with:
            name: "Continuous Build (${{ env.APP_VERSION }})"
            tag_name: "nightly"
            prerelease: true
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
